---
title: "Preprocessor"
output: html_notebook
---

```{r}
renv::activate()
library(tidyverse)
```

# Load data

```{r}
data <- bind_rows(
  read_csv('../facebook-scraper/out/166477880066544_12323_201129.csv') %>% mutate(group = 'Expats in Tallinn/Estonia'),
  read_csv('../facebook-scraper/out/1395659303995885_12323_203310.csv') %>% mutate(group = 'Expats in Tallinn, Estonia'),
  read_csv('../facebook-scraper/out/ExpatsEstonia_12323_204417.csv') %>% mutate(group = 'Expats & Foreigners in Estonia')
)

data
```

# Clean the data

```{r}
end_date <- as.numeric(as.POSIXct("2023-01-01", format="%Y-%m-%d"))

clean_data <- data %>%
  select(-top_level_post_id, -actor_id) %>%
  filter(publish_time < end_date*1000, !is.na(text)) %>%
  arrange(desc(publish_time)) %>%
  mutate(date = as.Date.POSIXct(publish_time/1000)) %>%
  separate(date, c('year', 'month', 'day'), '-', remove = TRUE, convert = TRUE) %>%
  select(-year) %>%
  rename(timestamp = publish_time, attachment = ent_attachement_type) %>%
  mutate(text = gsub('\n', '', text, fixed = TRUE), attachment = gsub('Attachment', '', attachment, fixed = TRUE)) %>%
  relocate(timestamp, .after = day) %>%
  relocate(text, attachment, .after = timestamp)

clean_data
```


# EDA

## Group


```{r}
clean_data %>%
  group_by(group) %>%
  count() %>%
ggplot(aes(x = reorder(group, -n), y = n, label = n)) +
  geom_bar(stat = 'identity') +
  geom_text(vjust = -0.2) +
  labs(
    title = 'Number of posts from each group',
    x = 'Facebook group',
    y = 'Number of posts')
```

## Published month

```{r}
clean_data %>%
  group_by(month) %>%
  count() %>%
  summary()
```

```{r}
ggplot(clean_data, aes(x = as.factor(month), fill = group)) +
  geom_bar() +
  labs(
    title = 'Number of posts in each month',
    x = 'Month',
    y = 'Number of posts',
    fill = 'Group')
```

## Text

```{r}
summary(nchar(clean_data$text))
```


```{r}
ggplot(clean_data, aes(x = nchar(text))) +
  geom_histogram(bins = 40) +
  labs(
    title = 'Text length distribution',
    x = 'Text length',
    y = 'Number of posts')
```
```{r}
ggplot(clean_data, aes(y = nchar(text))) +
  geom_boxplot() +
  labs(
    title = 'Text length distribution in each Facebook group',
    y = 'Text length',
    x = 'Number of posts') +
  facet_wrap('group')
```

```{r}
clean_data %>%
  mutate(attachment = replace_na(attachment, 'No attachment')) %>%
  group_by(attachment) %>%
  count() %>%
ggplot(aes(x = n, y = reorder(attachment, n), label = n )) +
  geom_bar(stat = 'identity') +
  geom_text(size = 2.5, hjust = -0.1) +
  labs(
    title = 'Number of posts by attachment type',
    y = 'Attachment type',
    x = 'Number of posts')
```

```{r}
clean_data %>%
  mutate(attachment = replace_na(attachment, 'No attachment')) %>%
ggplot(aes(x = nchar(text), y = reorder(attachment, attachment, length))) +
  geom_boxplot() +
  labs(
    title = 'Attachment type and text length of posts',
    y = 'Attachment type',
    x = 'Text length')
```

# Write output

```{r}
clean_data %>%
  select(-attachment) %>%
  distinct(text, .keep_all = TRUE) %>%
  write_csv('cleaned_data.csv')
```